[build]
  publish = "dist"                           # yeh frontend/dist ko point karega
  command = "npm install && npm run build"   # safe hai, dependencies install karega

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
  force  = true                              # optional but helpful